//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2024/4/13 23:21:14
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace MVVM6
{
    public partial class User {

        public User()
        {
            OnCreated();
        }

        public User(int id, int? age, string? email, string name)
        {
            Id = id;
            Age = age;
            Email = email;
            Name = name;
        }

        public int Id { get; set; }

        public int? Age { get; set; }

        public string? Email { get; set; }

        public string Name { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
